### ISSUE TITLE
Crash app v1.0.1

### ISSUE THREAD

**Issue by userkilled** [aleksey-saenko/MusicRecognizer#6]
FATAL EXCEPTION: e9.z Dispatcher
Process: com.mrsep.musicrecognizer, PID: 5465
java.lang.IllegalStateException: Unbalanced enter/exit
	at r9.d.i(Unknown Source:126)
	at r9.c.M(Unknown Source:19)
	at r9.b0.a(Unknown Source:49)
	at r9.b0.w(Unknown Source:38)
	at k9.h.f(Unknown Source:24)
	at i9.e.d(Unknown Source:2)
	at j9.b.a(Unknown Source:283)
	at j9.f.b(Unknown Source:134)
	at i9.a.a(Unknown Source:101)
	at j9.f.b(Unknown Source:134)
	at g9.b.a(Unknown Source:121)
	at j9.f.b(Unknown Source:134)
	at j9.a.a(Unknown Source:150)
	at j9.f.b(Unknown Source:134)
	at j9.g.a(Unknown Source:153)
	at j9.f.b(Unknown Source:134)
	at i9.j.g(Unknown Source:95)
	at i9.g.run(Unknown Source:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

---

I touch 'Listen', app crashed.

**Comment by userkilled** [comment]
I use Blackview BV6300Pro / Android 10

**Comment by nutpantz** [comment]
Crash here also Samsung tab 7 lite Android 13

**Comment by aleksey-saenko** [comment]
@userkilled 
@nutpantz 
Thanks for reporting and providing stack trace!
Could you please check these builds? If the first one works, there's no need to test the second one.
[audile_d1.zip](https://github.com/aleksey-saenko/MusicRecognizer/files/13235993/audile_d1.zip)
[audile_d2.zip](https://github.com/aleksey-saenko/MusicRecognizer/files/13235997/audile_d2.zip)

**Comment by userkilled** [comment]
First one great works

**Comment by nutpantz** [comment]
One is crashing for me half the time testing 2 now

**Comment by nutpantz** [comment]
One is crashing for me half the time 
2 worked twice then i hit the token limit

**Comment by userkilled** [comment]
I testing Second version,  great works

**Comment by nutpantz** [comment]
Yes got an api key for testing and#2 has not crashed yet on 4 songs

**Comment by aleksey-saenko** [comment]
Thanks for testing! The fix will be included in the next release.

**Comment by nutpantz** [comment]
I went back and tested #1 again and it's not crashing.
Maybe i got confused the first test. Or the different api key made a difference

**Comment by XieyilinMain** [comment]
the same in Redmi K50, Android 13

**Comment by aleksey-saenko** [comment]
Version 1.1.0, including the bug fix, was released on F-Droid.
